env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
rules:
  no-use-before-define: 'off'              # recursive functions make this impossible
  strict: 'off'
  comma-dangle: 'off'
  no-template-curly-in-string: 'off'
  import/no-extraneous-dependencies: 'off'  # Gruntfile devDependencies
  no-param-reassign: 'off'
  prefer-spread: 'off'
  prefer-rest-params: 'off'
  max-len: ['error', 140, 2, {              # Set max line length to 140 chars
    ignoreUrls: true,
    ignoreComments: false,
    ignoreRegExpLiterals: true,
    ignoreStrings: true,
    ignoreTemplateLiterals: true,
  }]
